// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADTAu4LlhuuPZ3_lgkVYRQH4Djp1L42WM',
    appId: '1:1082474782259:web:44f67450a8150f91168d46',
    messagingSenderId: '1082474782259',
    projectId: 'batch10auth',
    authDomain: 'batch10auth.firebaseapp.com',
    storageBucket: 'batch10auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmyd5flDIKvgpXy_L9mpbQFJJNJTTAwqI',
    appId: '1:1082474782259:android:4a3af33ea9eaaed0168d46',
    messagingSenderId: '1082474782259',
    projectId: 'batch10auth',
    storageBucket: 'batch10auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYQRWZOnVbPEn1nmdNIgh1FDENh0xgzsI',
    appId: '1:1082474782259:ios:38f87ca1877f9171168d46',
    messagingSenderId: '1082474782259',
    projectId: 'batch10auth',
    storageBucket: 'batch10auth.firebasestorage.app',
    androidClientId: '1082474782259-pj86eisfl1vg7vb2oa3e3hj12e72kq86.apps.googleusercontent.com',
    iosClientId: '1082474782259-3s529t608plq5fgjencu37dpjvs1pjra.apps.googleusercontent.com',
    iosBundleId: 'com.example.batch10auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYQRWZOnVbPEn1nmdNIgh1FDENh0xgzsI',
    appId: '1:1082474782259:ios:38f87ca1877f9171168d46',
    messagingSenderId: '1082474782259',
    projectId: 'batch10auth',
    storageBucket: 'batch10auth.firebasestorage.app',
    androidClientId: '1082474782259-pj86eisfl1vg7vb2oa3e3hj12e72kq86.apps.googleusercontent.com',
    iosClientId: '1082474782259-3s529t608plq5fgjencu37dpjvs1pjra.apps.googleusercontent.com',
    iosBundleId: 'com.example.batch10auth',
  );

}